---
name: ci

"on":
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"

  json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run JSON Lint
        run: |
          git ls-files *.json | xargs jq empty

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main
